In [9]:
                                                  #Question 2 

import numpy as np
arr1 = np.random.randint(0, 200, size=(3,4))     #generation of randon array
print(arr1)


[[ 23 147  68  46]
 [ 48 184   4 157]
 [197 116  83 182]]


In [10]:
                                                   #Part - a
#mean
mean_arr = np.mean(arr1, axis=1)
print(mean_arr)

#standard Deviation
std_arr= np.std(arr1, axis=1)
print(std_arr)

#Variance
variance_arr = np.var(arr1, axis=1)
print(variance_arr)

[ 71.    98.25 144.5 ]
[46.67440412 74.51971216 46.78942188]
[2178.5    5553.1875 2189.25  ]


In [11]:
                                                #Part - b
B = np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])
indices = np.argsort(B)
print(indices)

[8 2 6 9 3 7 1 0 4 5]


In [12]:
                                              #Part - c
m = int(input("Enter the number of rows(m) : "))
n = int(input("Enter the number of columns(n) : "))
arr2 = np.random.randint(0, 100, size=(m, n))
print(arr2)

print("Shape of array  :", arr2.shape)
print("Type of array  :", type(arr2))
print("Data type :", arr2.dtype)

reshaped_array = arr2.reshape(n, m)
print("Reshaped array :", reshaped_array)

Enter the number of rows(m) : 3
Enter the number of columns(n) : 2
[[94 37]
 [20  5]
 [46 30]]
Shape of array  : (3, 2)
Type of array  : <class 'numpy.ndarray'>
Data type : int32
Reshaped array : [[94 37 20]
 [ 5 46 30]]


In [13]:
                                          #Part - d
arr2 = np.array([10, 3, 25, 52, 0, np.nan, 0, np.nan])

zero_indices = np.where(arr2 == 0)[0]
non_zero_indices = np.where(arr2 != 0)[0]
nan_indices = np.where(np.isnan(arr2))[0]

print("Array:", arr2)
print("Indices of Zero Elements are ", zero_indices)
print("Indices of Non-Zero Elements are", non_zero_indices)
print("Indices of NaN Elements are", nan_indices)

Array: [10.  3. 25. 52.  0. nan  0. nan]
Indices of Zero Elements are  [4 6]
Indices of Non-Zero Elements are [0 1 2 3 5 7]
Indices of NaN Elements are [5 7]
